import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";
import { TrabalhosProvider } from "@/contexts/TrabalhosProvider";
import Rodape from "@/components/Rodape";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "muratore portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="flex min-h-screen min-w-screen">
      <body
        className={`flex px-4 flex-col min-h-screen min-w-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TrabalhosProvider>
            <Header />

            
            {children}

           <div className="flex-grow"></div>
          
                      
            <Rodape/>
          </TrabalhosProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
